-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 10:08:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema copa_mundo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema copa_mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `copa_mundo` DEFAULT CHARACTER SET utf8 ;
USE `copa_mundo` ;

-- -----------------------------------------------------
-- Table `copa_mundo`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`grupo` (
  `idgrupo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`pais` (
  `idpais` INT NOT NULL,
  `selecao` VARCHAR(45) NULL DEFAULT NULL,
  `continente` VARCHAR(45) NULL DEFAULT NULL,
  `tecnico` VARCHAR(45) NULL DEFAULT NULL,
  `pontos` INT NULL DEFAULT NULL,
  `vitorias` INT NULL DEFAULT NULL,
  `empates` INT NULL DEFAULT NULL,
  `derrotas` INT NULL DEFAULT NULL,
  `golspro` INT NULL DEFAULT NULL,
  `golscontra` INT NULL DEFAULT NULL,
  `grupo_idgrupo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`),
  INDEX `fk_pais_grupo_idx` (`grupo_idgrupo` ASC) VISIBLE,
  CONSTRAINT `fk_pais_grupo`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `copa_mundo`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`estadio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`estadio` (
  `idestadio` INT NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `localizacao` VARCHAR(45) NULL DEFAULT NULL,
  `capacidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idestadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`jogos` (
  `idrodada` INT NOT NULL,
  `data` TIMESTAMP NULL DEFAULT NULL,
  `estadio_idestadio` INT NOT NULL,
  `pais_idpais_1` INT NOT NULL,
  `pais_idpais_2` INT NOT NULL,
  `gols_idpais_1` INT NULL DEFAULT NULL,
  `gols_idpais_2` INT NULL DEFAULT NULL,
  `publico` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idrodada`),
  INDEX `fk_jogos_estadio1_idx` (`estadio_idestadio` ASC) VISIBLE,
  INDEX `fk_jogos_pais1_idx` (`pais_idpais_2` ASC) VISIBLE,
  INDEX `fk_jogos_pais2_idx` (`pais_idpais_1` ASC) VISIBLE,
  CONSTRAINT `fk_jogos_estadio1`
    FOREIGN KEY (`estadio_idestadio`)
    REFERENCES `copa_mundo`.`estadio` (`idestadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_pais1`
    FOREIGN KEY (`pais_idpais_2`)
    REFERENCES `copa_mundo`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_pais2`
    FOREIGN KEY (`pais_idpais_1`)
    REFERENCES `copa_mundo`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`jogador` (
  `idjogador` INT NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `camisa` INT NULL DEFAULT NULL,
  `posicao` VARCHAR(45) NULL DEFAULT NULL,
  `pais_idpais` INT NOT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idjogador`),
  INDEX `fk_jogador_pais1_idx` (`pais_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_jogador_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `copa_mundo`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`cartao` (
  `jogos_idrodada` INT NOT NULL,
  `jogador_idjogador` INT NOT NULL,
  `amarelo` TINYINT NULL DEFAULT NULL,
  `vermelho` TINYINT NULL DEFAULT NULL,
  `tempo` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_cartao_jogos1_idx` (`jogos_idrodada` ASC) VISIBLE,
  INDEX `fk_cartao_jogador1_idx` (`jogador_idjogador` ASC) VISIBLE,
  CONSTRAINT `fk_cartao_jogos1`
    FOREIGN KEY (`jogos_idrodada`)
    REFERENCES `copa_mundo`.`jogos` (`idrodada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartao_jogador1`
    FOREIGN KEY (`jogador_idjogador`)
    REFERENCES `copa_mundo`.`jogador` (`idjogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`gols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`gols` (
  `jogo_idrodada` INT NOT NULL,
  `jogador_idjogador` INT NOT NULL,
  `tempo` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_gols_jogos1_idx` (`jogo_idrodada` ASC) VISIBLE,
  INDEX `fk_gols_jogador1_idx` (`jogador_idjogador` ASC) VISIBLE,
  CONSTRAINT `fk_gols_jogos1`
    FOREIGN KEY (`jogo_idrodada`)
    REFERENCES `copa_mundo`.`jogos` (`idrodada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gols_jogador1`
    FOREIGN KEY (`jogador_idjogador`)
    REFERENCES `copa_mundo`.`jogador` (`idjogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`substituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_mundo`.`substituicao` (
  `jogos_idrodada` INT NOT NULL,
  `jogador_idjogador_sai` INT NOT NULL,
  `jogador_idjogador_entra` INT NOT NULL,
  `tempo` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_substituicao_jogador1_idx` (`jogador_idjogador_sai` ASC) VISIBLE,
  INDEX `fk_substituicao_jogador2_idx` (`jogador_idjogador_entra` ASC) VISIBLE,
  CONSTRAINT `fk_substituicao_jogos1`
    FOREIGN KEY (`jogos_idrodada`)
    REFERENCES `copa_mundo`.`jogos` (`idrodada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_substituicao_jogador1`
    FOREIGN KEY (`jogador_idjogador_sai`)
    REFERENCES `copa_mundo`.`jogador` (`idjogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_substituicao_jogador2`
    FOREIGN KEY (`jogador_idjogador_entra`)
    REFERENCES `copa_mundo`.`jogador` (`idjogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
